format = 1

[pack]
name = "FOREVER WORLD"
slug = "forever-world"
version = "1.2.0"
group = "com.iamkaf.modpacks"
minecraft = "26.2"
loader = "fabric"
loader_version = "0.19.3"

[mods]
amber = "11.1.2+26.2"
appleskin = "3.0.10+mc26.2"
bl4cks-sit = "v1.5.1"
bonded = "4.1.0+26.2"
c2me-fabric = "0.4.2-alpha.0.13+26.2"
creativecore = "2.14.16"
fabric-api = "0.154.2+26.2"
fabric-language-kotlin = "1.13.12+kotlin.2.4.0"
ferrite-core = "9.0.0-fabric"
forge-config-api-port = "26.2.1"
happyghastimprovements = "2.1.0+26.2"
jei = "30.9.0.57"
kafs-valentine-special = "5.1.0+26.2"
konfig = "0.5.0+26.2"
liteminer = "4.1.1+26.2"
lithium = "mc26.2-0.25.2-fabric"
mochila = "6.1.0+26.2"
mru = "1.0.30+26.2-fabric"
placeholder-api = "3.1.0-beta.1+26.2"
puzzles-lib = "26.2.0"
snapshears = "5.1.0+26.2"
sound-physics-remastered = "fabric-1.5.1+26.2"
torch-toss = "5.1.0+26.2"
yacl = "3.9.5+26.2-fabric"

[client_mods]
3dskinlayers = "1.11.2"
ambientsounds = "6.3.6"
bobby = "5.2.14+mc26.2"
chat-heads = "1.2.4"
controlling = "26.2.2"
cubes-without-borders = "4.1.0+26.2"
cut-through = "26.2.0"
entityculling = "1.10.5"
gentlehurtcam = "2.1.0+26.2"
immediatelyfast = "1.16.1+26.2-fabric"
iris = "1.11.2+26.2-fabric"
kaf-hud = "6.1.0+26.2"
lambdynamiclights = "4.12.2+26.2"
libipn = "fabric-26.2-6.8.2"
modmenu = "20.0.1"
mouse-tweaks = "26.2-2.31-fabric"
particle-effects = "1.5.0+26.2+fabric"
presence-footsteps = "1.13.3+26.2"
rrls = "5.2.7+mc26.2"
searchables = "1.0.1"
sodium = "mc26.2-0.9.1-fabric"
sound = "2.5.1+edge+26.2-fabric"
zoomify = "2.16.1+26.2"

[shaders]
complementary-unbound = "r5.7.1"

[publish]
changelog = "CHANGELOG.md"

[publish.modrinth]
project = "TRgAveYb"

[publish.github]
repository = "iamkaf/forever-world"

[publish.maven]
repository = "https://z.kaf.sh/releases"

[publish.curseforge]
project = 1663962
author = "iamkaf"
