#!/usr/bin/env python3
"""Render the pack-owned Modstage instances from the lockfile."""

from __future__ import annotations

from pathlib import Path
import argparse
import tomllib


TEAKIT_VERSION = "0.14.0"


def quote(value: str) -> str:
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


def cache_path(file: dict) -> str:
    return f"../.cache/objects/{file['sha512']}"


def server_file(file: dict) -> bool:
    return file["env"]["server"] != "unsupported"


def client_file(file: dict) -> bool:
    return file["env"]["client"] != "unsupported"


def write_instance(
    output: list[str],
    name: str,
    pack: dict,
    sides: tuple[str, ...],
    mods: tuple[str, ...] = (),
    server_properties: bool = False,
) -> None:
    output.extend(
        [
            "",
            "[[instance]]",
            f"name = {quote(name)}",
            f"minecraft = {quote(pack['minecraft'])}",
            f"loader = {quote(pack['loader'])}",
            f"loader_version = {quote(pack['loader_version'])}",
            f"sides = [{', '.join(quote(side) for side in sides)}]",
        ]
    )
    if server_properties:
        output.append(
            'server_properties = { online-mode = "false", enforce-secure-profile = "false" }'
        )
    output.extend(["mods = [", *(f"  {quote(mod)}," for mod in mods)])
    output.append("]")


def write_fixtures(
    output: list[str], files: list[dict], side: str | None = None
) -> None:
    for file in files:
        fixture = [
            "",
            "[[instance.fixture]]",
            f"from = {quote(cache_path(file))}",
            f"to = {quote(file['path'])}",
        ]
        if side is not None:
            fixture.append(f"side = {quote(side)}")
        fixture.append("replace = true")
        output.extend(fixture)


def render(lock: dict) -> str:
    pack = lock["pack"]
    files = lock["file"]
    client_files = [file for file in files if client_file(file)]
    server_files = [file for file in files if server_file(file)]
    shared_files = [file for file in files if client_file(file) and server_file(file)]
    client_only_files = [
        file for file in files if client_file(file) and not server_file(file)
    ]
    server_only_files = [
        file for file in files if server_file(file) and not client_file(file)
    ]
    teakit = (
        f"maven:com.iamkaf.teakit:teakit-fabric:{TEAKIT_VERSION}+{pack['minecraft']}"
    )

    output = [
        "# Generated by scripts/render_modstage.py from pack.lock.toml. Do not edit.",
        "[project]",
        f"name = {quote(pack['slug'])}",
        "",
        "[repositories]",
        'mavenLocal = "mavenLocal"',
        'kaf = "https://maven.kaf.sh"',
    ]
    write_instance(
        output,
        f"{pack['slug']}-server",
        pack,
        ("server",),
        server_properties=True,
    )
    write_fixtures(output, server_files)
    write_instance(output, f"{pack['slug']}-client", pack, ("client",))
    write_fixtures(output, client_files)
    write_instance(
        output,
        f"{pack['slug']}-pair",
        pack,
        ("client", "server"),
        mods=(teakit,),
        server_properties=True,
    )
    write_fixtures(output, shared_files)
    write_fixtures(output, client_only_files, side="client")
    write_fixtures(output, server_only_files, side="server")
    return "\n".join(output) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", type=Path, default=Path(__file__).resolve().parents[1])
    parser.add_argument("--output", type=Path, default=None)
    args = parser.parse_args()
    root = args.root.resolve()
    with (root / "pack.lock.toml").open("rb") as stream:
        lock = tomllib.load(stream)
    output = args.output or root / "generated" / "modstage.toml"
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(render(lock), encoding="utf-8")
    print(output)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
