#!/usr/bin/env python3
"""Render the pack-owned Modstage instances from the lockfile."""

from __future__ import annotations

from pathlib import Path
import argparse
import tomllib


TEAKIT_VERSION = "0.14.0"


def quote(value: str) -> str:
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


def cache_path(file: dict) -> str:
    return f"../.cache/objects/{file['sha512']}"


def server_file(file: dict) -> bool:
    return file["env"]["server"] != "unsupported"


def client_file(file: dict) -> bool:
    return file["env"]["client"] != "unsupported"


def write_instance(
    output: list[str],
    name: str,
    pack: dict,
    sides: tuple[str, ...],
    mods: list[dict],
    extras: tuple[str, ...] = (),
    server_properties: bool = False,
) -> None:
    output.extend(
        [
            "",
            "[[instance]]",
            f"name = {quote(name)}",
            f"minecraft = {quote(pack['minecraft'])}",
            f"loader = {quote(pack['loader'])}",
            f"loader_version = {quote(pack['loader_version'])}",
            f"sides = [{', '.join(quote(side) for side in sides)}]",
        ]
    )
    if server_properties:
        output.append(
            'server_properties = { online-mode = "false", enforce-secure-profile = "false" }'
        )
    output.extend(["mods = [", *(f"  {quote(cache_path(file))}," for file in mods)])
    output.extend(f"  {quote(extra)}," for extra in extras)
    output.append("]")


def write_fixtures(output: list[str], files: list[dict]) -> None:
    for file in files:
        output.extend(
            [
                "",
                "[[instance.fixture]]",
                f"from = {quote(cache_path(file))}",
                f"to = {quote(file['path'])}",
                'side = "client"',
                "replace = true",
            ]
        )


def render(lock: dict) -> str:
    pack = lock["pack"]
    files = lock["file"]
    client_mods = [
        file
        for file in files
        if client_file(file) and file["path"].startswith("mods/")
    ]
    client_only_mods = [
        file
        for file in files
        if client_file(file) and not server_file(file) and file["path"].startswith("mods/")
    ]
    shaders = [file for file in files if client_file(file) and file["path"].startswith("shaderpacks/")]
    server_mods = [file for file in files if server_file(file)]
    teakit = (
        f"maven:com.iamkaf.teakit:teakit-fabric:{TEAKIT_VERSION}+{pack['minecraft']}"
    )

    output = [
        "# Generated by scripts/render_modstage.py from pack.lock.toml. Do not edit.",
        "[project]",
        f"name = {quote(pack['slug'])}",
        "",
        "[repositories]",
        'mavenLocal = "mavenLocal"',
        'kaf = "https://maven.kaf.sh"',
    ]
    write_instance(
        output,
        f"{pack['slug']}-server",
        pack,
        ("server",),
        server_mods,
        server_properties=True,
    )
    write_instance(output, f"{pack['slug']}-client", pack, ("client",), client_mods)
    write_fixtures(output, shaders)
    write_instance(
        output,
        f"{pack['slug']}-pair",
        pack,
        ("client", "server"),
        server_mods,
        extras=(teakit,),
        server_properties=True,
    )
    write_fixtures(output, client_only_mods)
    write_fixtures(output, shaders)
    return "\n".join(output) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", type=Path, default=Path(__file__).resolve().parents[1])
    parser.add_argument("--output", type=Path, default=None)
    args = parser.parse_args()
    root = args.root.resolve()
    with (root / "pack.lock.toml").open("rb") as stream:
        lock = tomllib.load(stream)
    output = args.output or root / "generated" / "modstage.toml"
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(render(lock), encoding="utf-8")
    print(output)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
